checks:
    php: true
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 1200    # Timeout in seconds.    
    
filter:
    excluded_paths:
        - tests/*   
