language: php
sudo: false
dist: trusty
sudo: false
php:
 - "7.1"
 - "7.2"
env: COVERAGE=yes
 
before_script:
 - composer install

script: vendor/bin/phpunit --coverage-clover coverage.clover -c tests/config.xml
after_script: if [ "$COVERAGE" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

